## Numpy Operations

In [3]:
import numpy as np

# Example: Creating arrays
arr = np.array([1, 2, 3, 4])
print("Array:", arr)

# Example: Array operations
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))


Array: [1 2 3 4]
Sum: 10
Mean: 2.5


In [4]:
# Slicing

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)
print("Sliced Array:\n", arr[1:, 1:])


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced Array:
 [[5 6]
 [8 9]]


In [5]:
#Math
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Array:", arr)
print("Square:", np.square(arr))
print("Square Root:", np.sqrt(arr))


Array: [1 2 3 4]
Square: [ 1  4  9 16]
Square Root: [1.         1.41421356 1.73205081 2.        ]


In [6]:
#Searching

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr == 30)
print("Index of 30:", result[0])


Index of 30: [2]


In [7]:
#Sorting

import numpy as np

arr = np.array([5, 3, 8, 1, 2])
sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)


Sorted Array: [1 2 3 5 8]
